version : '3.7'
services:
  mongo:
    image: mongo:6.0-focal
    container_name: data-cave-db
    ports:
      - "27018:27017"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_INITDB_DATABASE=dataCave
    volumes:
      - mongodbdata:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
volumes:
  mongodbdata:
    # driver: local
  # scripts:
